blank_issues_enabled: false

contact_links:
  - name: 💬 Forum
    url: https://github.com/vbti-development/onedl-mmcv/discussions
    about: Ask general usage questions and discuss with other mmcv community members
  - name: MMCV Documentation
    url: https://onedl-mmcv.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
