name: merge_stage_test

on:
  push:
    paths-ignore:
      - ".github/**.md"
      - "docker/**"
      - "docs/**"
      - 'examples/**'
      - '.dev_scripts/**'
      - "README.md"
      - "README_zh-CN.md"
      - "CONTRIBUTING.md"
      - ".pre-commit-config.yaml"
      - ".pre-commit-config-zh-cn.yaml"
    # branches:
    #   - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_without_torch:
    runs-on: ubuntu-22.04
    env:
      MMCV_WITH_OPS: 0
    strategy:
      matrix:
        python-version: ['3.10']
    steps: 
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg libturbojpeg python3-dev
      - name: Install MMEngine from main branch
        run: uv pip install git+https://github.com/VBTI-development/mmengine.git@main
      - name: Install build requirements
        run: uv pip install -r pyproject.toml --extra build
      - name: Build MMCV from source
        run: uv pip install -e . -v
      - name: Install unit tests dependencies
        run: uv pip install -r pyproject.toml --extra test
      - name: Run unit tests
        run: uv run pytest tests/test_image tests/test_transforms tests/test_video tests/test_arraymisc.py tests/test_visualization.py tests/test_utils/test_env.py --ignore=tests/test_image/test_io.py
  build_without_ops:
    runs-on: ubuntu-22.04
    env:
      MMCV_WITH_OPS: 0
    strategy:
      matrix:
        python-version: ['3.10']
        torch: [2.4.1]
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg libturbojpeg python3-dev
      - name: Install PyTorch
        run: |
          uv pip install torch==${{ matrix.torch }} torchvision
      - name: Install MMEngine from main branch
        run: uv pip install git+https://github.com/VBTI-development/mmengine.git@main
      - name: Install build requirements
        run: uv pip install -r pyproject.toml --extra build
      - name: Build MMCV from source
        run: uv pip install -e . -v
      - name: Install unit tests dependencies
        run: uv pip install -r pyproject.toml --extra test
      - name: Run unit tests
        run: pytest tests --ignore=tests/test_ops
  build_cpu_py:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']
        torch: [2.3.1]
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg libturbojpeg python3-dev
      - name: Install PyTorch
        run: |
          uv pip install torch==${{ matrix.torch }} torchvision
      - name: Install MMEngine from main branch
        run: uv pip install git+https://github.com/VBTI-development/mmengine.git@main
      - name: Install build requirements
        run: uv pip install -r pyproject.toml --extra build
      - name: Build MMCV from source
        run: uv pip install -e . -v
      - name: Install unit tests dependencies
        run: uv pip install -r pyproject.toml --extra test
      - name: Run unit tests
        run: pytest tests

  build_cpu_pt:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']
        torch: [ '2.0.0', '2.1.0', '2.3.1', '2.4.1', '2.5.1']
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg libturbojpeg python3-dev
      - name: Install PyTorch
        run: |
          uv pip install torch==${{ matrix.torch }} torchvision
      - name: Install MMEngine from main branch
        run: uv pip install git+https://github.com/VBTI-development/mmengine.git@main
      - name: Install build requirements
        run: uv pip install -r pyproject.toml --extra build
      - name: Build MMCV from source
        run: uv pip install -e . -v
      - name: Install unit tests dependencies
        run: uv pip install -r pyproject.toml --extra test
      - name: Run unit tests
        run: pytest tests

  build_cu118:
    runs-on: ubuntu-22.04
    container:
      # image: pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime
      image: nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04
    strategy:
      matrix:
        python-version: ['3.10']
        torch: [2.3.1]
    env:
      FORCE_CUDA: 1
      MMCV_CUDA_ARGS: -gencode=arch=compute_61,code=sm_61
      UV_TORCH_BACKEND: auto
      #python 3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install basic tools
        run: |
          apt-get update
          apt-get install -y wget build-essential git software-properties-common

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 安装 PyTorch
      - name: Fetch GPG keys
        run: |
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
      - name: Install system dependencies
        run: apt-get update && apt-get install -y git ffmpeg libturbojpeg python3-dev
      - name: Install PyTorch
        run: |
          uv pip install torch==${{ matrix.torch }} torchvision
      - name: Install MMEngine from main branch
        run: uv pip install git+https://github.com/VBTI-development/mmengine.git@main
      - name: Install ninja to speed the compilation
        run: uv pip install -r pyproject.toml --extra optional --extra build
      - name: Build MMCV from source
        run: uv pip install -e . -v
      - name: Install unit tests dependencies
        run: |
          uv pip install -r pyproject.toml --extra test
      - name: Run unittests
        run: |
          uv run pytest tests/

  build_windows_without_ops:
    runs-on: windows-2025
    env:
      MMCV_WITH_OPS: 0
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PyTorch
        run: |
          uv pip install torch==${{ matrix.torch }} torchvision
      - name: Install MMEngine from main branch
        run: uv pip install git+https://github.com/VBTI-development/mmengine.git@main
      - name: Install ninja to speed the compilation
        run: uv pip install -r pyproject.toml --extra optional --extra build
      - name: Build MMCV from source
        run: uv pip install -e . -v
      - name: Install unit tests dependencies
        run: |
          uv pip install -r pyproject.toml --extra test
      - name: Run unittests
        run: uv run pytest tests --ignore=tests/test_ops --ignore tests/test_image/test_io.py

  build_windows:
    runs-on: windows-2025
    strategy:
      matrix:
        torch: [2.1.0]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PyTorch
        run: |
          uv pip install torch==${{ matrix.torch }} torchvision
      - name: Install MMEngine from main branch
        run: uv pip install git+https://github.com/VBTI-development/mmengine.git@main
      - name: Install ninja to speed the compilation
        run: uv pip install -r pyproject.toml --extra optional --extra build
      - name: Build MMCV from source
        run: uv pip install -e . -v
      - name: Install unit tests dependencies
        run: |
          uv pip install -r pyproject.toml --extra test
      - name: Run unittests
        run: uv run pytest tests/ --ignore tests/test_image/test_io.py
