name: deploy

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-n-publish_without_ops:
    runs-on: ubuntu-22.04
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.10
      - name: Build MMCV
        run: |
          sed -i "s/os.getenv('MMCV_WITH_OPS', '1')/os.getenv('MMCV_WITH_OPS', '0')/g" setup.py
          uv build --sdist --wheel
      - name: Publish distribution to PyPI
        run: |
          uv publish --index testpypi

  build-n-publish_with_ops:
    runs-on: ubuntu-22.04
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.10
      - name: Build MMCV
        run: |
          sed -i "s/os.getenv('MMCV_WITH_OPS', '1')/os.getenv('MMCV_WITH_OPS', '0')/g" setup.py
          uv build --sdist
      - name: Publish distribution to PyPI
        run: |
          uv publish --index testpypi