name: deploy

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-n-publish_with_ops:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'
      - name: Install ninja to speed the compilation
        run: uv pip install -r pyproject.toml --group optional  --group build
      - name: Build MMCV
        run: |
          uv build --sdist
      - name: Publish distribution to PyPI
        run: |
          uv publish
