name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'     # Production releases
      - 'v[0-9]+.[0-9]+.[0-9]+-*'   # Pre-releases with suffixes
  pull_request:

jobs:
  publish-cuda-to-wheelhouse:
    strategy:
      matrix:
        cuda: [11.8.0, 12.6.3, 12.8.1]
        pytorch: [2.4.1, 2.5.1, 2.7.1]
    runs-on: ubuntu-24.04
    env:
      CUDA: ${{ matrix.cuda }}
      PYTORCH: ${{ matrix.pytorch }}
      TORCH_CUDA_ARCH_LIST: "7.5 8.0 8.6 8.9 9.0"
      CUDNN: ${{ matrix.cuda == '12.3' && '9' || (contains(matrix.cuda, '.') && (tonumber(split(matrix.cuda, '.')[0]) < 12 || (tonumber(split(matrix.cuda, '.')[0]) == 12 && tonumber(split(matrix.cuda, '.')[1]) < 3)) && '8' || '') }}

    steps:
      - uses: actions/checkout@v3

      - name: Update TORCH_CUDA_ARCH_LIST for CUDA >= 12.8
        run: |
          MAJOR=$(echo "${{ matrix.cuda }}" | cut -d. -f1)
          MINOR=$(echo "${{ matrix.cuda }}" | cut -d. -f2)
          PATCH=$(echo "${{ matrix.cuda }}" | cut -d. -f3)

          if [ $MAJOR -gt 12 ] || \
            ([ $MAJOR -eq 12 ] && [ $MINOR -gt 8 ]) || \
            ([ $MAJOR -eq 12 ] && [ $MINOR -eq 8 ]); then
              echo "TORCH_CUDA_ARCH_LIST=${{ env.TORCH_CUDA_ARCH_LIST }} 10.0 12.0" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker/build
          push: false
          tags: mmcv-builder:cu${{ env.CUDA }}-torch${{ env.PYTORCH }}
          load: true  # Load image into local Docker daemon
          build-args: |
            CUDA=${{ env.CUDA }}
            PYTORCH=${{ env.PYTORCH }}
            CUDNN=${{ env.CUDNN }}

      - name: Build wheel
        run: |
          docker run --rm \
          -e TORCH_CUDA_ARCH_LIST="${{ env.TORCH_CUDA_ARCH_LIST }}" \
          -v ${{ github.workspace }}/mmcv/dist:/out \
          mmcv-builder:cu${{ env.CUDA }}-torch${{ env.PYTORCH }}

      - name: List generated files
        run: |
            echo "Files to be uploaded to wheelhouse:"
            ls -la ./mmcv/dist

      - name: Upload to wheelhouse bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WHEELHOUSE_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WHEELHOUSE_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          CUDA_TRIMMED=${CUDA%.*}
          CUDA_CLEAN=${CUDA_TRIMMED//.}
          PYTORCH_CLEAN=${PYTORCH//.}
          aws s3 sync ./mmcv/dist/ s3://${{ secrets.WHEELHOUSE_S3_BUCKET }}/cu"$CUDA_CLEAN"-torch"$PYTORCH_CLEAN"/mmcv/ \
          --endpoint-url ${{ secrets.WHEELHOUSE_S3_ENDPOINT }} \
          --exclude '.gitignore'
